# -*- coding: utf-8 -*-
{
    'name': "supermodulo18",

    'summary': "Short (1 phrase/line) summary of the module's purpose",

    'description': """
Long description of module's purpose
    """,

    'author': "My Company",
    'website': "https://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': [

       
        
    'account',
    'account_add_gln',
    'account_banking_mandate',
    'account_banking_pain_base',
    'account_banking_sepa_direct_debit',
    'account_chart_update',
    'account_due_list',
    'account_due_list_payment_mode',
    'account_edi',
    'account_edi_proxy_client',
    'account_edi_ubl_cii',
    'account_invoice_line_report',
    'account_invoice_overdue_warn',
    'account_invoice_refund_link',
    'account_invoice_report_payment_info',
    'account_lock_date_update',
    'account_move_line_sale_info',
    'account_move_line_stock_info',
    'account_move_name_sequence',
    'account_move_template',
    'account_payment',
    'account_payment_mode',
    'account_payment_order',
    'account_payment_partner',
    'account_payment_promissory_note',
    'account_payment_purchase',
    'account_payment_purchase_stock',
    'account_payment_sale',
    'account_payment_term_extension',
    'account_peppol',
    'account_peppol_response',
    'account_peppol_selfbilling',
    'account_qr_code_sepa',
    'account_reconcile_model_oca',
    'account_reconcile_oca',
    'account_statement_base',
    'account_statement_import_base',
    'account_statement_import_file',
    'account_statement_import_file_reconcile_oca',
    'account_tax_balance',
    'account_usability',
    'analytic',
    'auth_signup',
    'auth_totp',
    'auth_totp_mail',
    'auth_totp_portal',
    'auto_backup',
    'barcodes',
    'barcodes_gs1_nomenclature',
    'base',
    'base_bank_from_iban',
    'base_iban',
    'base_import',
    'base_import_module',
    'base_install_request',
    'base_location',
    'base_location_geonames_import',
    'base_partner_sequence',
    'base_search_custom_field_filter',
    'base_setup',
    'base_sparse_field',
    'base_sparse_field_list_support',
    'base_technical_features',
    'base_vat',
    'board',
    'bus',
    'calendar',
    'calendar_sms',
    'certificate',
    'contacts',
    'contract',
    'contract_mandate',
    'contract_payment_mode',
    'crm',
    'crm_iap_enrich',
    'crm_iap_mine',
    'crm_sms',
    'date_range',
    'date_range_account',
    'digest',
    'disable_odoo_online',
    'document_knowledge',
    'document_page',
    'document_url',
    'google_gmail',
    'google_recaptcha',
    'hr',
    'hr_attendance',
    'hr_attendance_reason',
    'hr_calendar',
    'hr_expense',
    'hr_holidays',
    'hr_holidays_attendance',
    'hr_hourly_cost',
    'hr_org_chart',
    'hr_skills',
    'hr_timesheet',
    'hr_timesheet_attendance',
    'html_editor',
    'http_routing',
    'iap',
    'iap_crm',
    'iap_mail',
    'l10n_es',
    'l10n_es_account_asset',
    'l10n_es_account_banking_sepa_fsdd',
    'l10n_es_account_statement_import_n43',
    'l10n_es_aeat',
    'l10n_es_aeat_mod111',
    'l10n_es_aeat_mod115',
    'l10n_es_aeat_mod303',
    'l10n_es_aeat_mod347',
    'l10n_es_aeat_mod349',
    'l10n_es_aeat_mod390',
    'l10n_es_aeat_partner_check',
    'l10n_es_edi_facturae',
    'l10n_es_mis_report',
    'l10n_es_partner',
    'l10n_es_toponyms',
    'l10n_es_vat_book',
    'link_tracker',
    'login_user_detail',
    'mail',
    'mail_bot',
    'mail_bot_hr',
    'mass_mailing',
    'mass_mailing_crm',
    'mass_mailing_sale',
    'mass_mailing_themes',
    'mis_builder',
    'mis_builder_budget',
    'mrp',
    'mrp_account',
    'onboarding',
    'partner_autocomplete',
    'payment',
    'phone_validation',
    'portal',
    'portal_rating',
    'privacy_lookup',
    'product',
    'product_attribute_value_archive',
    'product_margin',
    'project',
    'project_account',
    'project_hr_expense',
    'project_hr_skills',
    'project_mrp',
    'project_mrp_account',
    'project_mrp_sale',
    'project_purchase',
    'project_purchase_stock',
    'project_sale_expense',
    'project_sms',
    'project_stock',
    'project_stock_account',
    'project_tag_hierarchy',
    'project_tag_multicompany',
    'project_tag_security',
    'project_todo',
    'project_timesheet_holidays',
    'purchase',
    'purchase_edi_ubl_bis3',
    'purchase_mrp',
    'purchase_product_template_tags',
    'purchase_stock',
    'rating',
    'remove_odoo_enterprise',
    'report_xlsx',
    'report_xlsx_helper',
    'resource',
    'resource_mail',
    'sale',
    'sale_async_emails',
    'sale_crm',
    'sale_edi_ubl',
    'sale_expense',
    'sale_mrp',
    'sale_pdf_quote_builder',
    'sale_product_template_tags',
    'sale_project',
    'sale_project_stock',
    'sale_project_stock_account',
    'sale_purchase',
    'sale_purchase_project',
    'sale_purchase_stock',
    'sale_service',
    'sale_sms',
    'sale_stock',
    'sale_timesheet',
    'sales_team',
    'server_action_mass_edit',
    'sms',
    'snailmail',
    'snailmail_account',
    'social_media',
    'spreadsheet',
    'spreadsheet_account',
    'spreadsheet_dashboard',
    'spreadsheet_dashboard_account',
    'spreadsheet_dashboard_hr_expense',
    'spreadsheet_dashboard_hr_timesheet',
    'spreadsheet_dashboard_purchase_oca',
    'spreadsheet_dashboard_purchase_stock_oca',
    'spreadsheet_dashboard_sale',
    'spreadsheet_dashboard_sale_timesheet',
    'spreadsheet_dashboard_stock_account',
    'stock',
    'stock_account',
    'stock_sms',
    'uom',
    'utm',
    'web',
    'web_chatter_position',
    'web_editor',
    'web_hierarchy',
    'web_no_bubble',
    'web_responsive',
    'web_tour',
    'web_unsplash'

],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}

