{
    'name': "supermodulo19",

    'summary': "Short (1 phrase/line) summary of the module's purpose",

    'description': """
Long description of module's purpose
    """,

    'author': "My Company",
    'website': "https://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': [
    'account',
'account_add_gln',
'account_banking_mandate',
'account_banking_mandate_sale',
'account_banking_pain_base',
'account_banking_sepa_direct_debit',
'account_comment_template',
'account_due_list',
'account_edi',
'account_edi_proxy_client',
'account_edi_ubl_cii',
'account_financial_report',
'account_fiscal_year',
'account_invoice_overdue_warn',
'account_invoice_overdue_warn_sale',
'account_invoice_refund_link',
'account_invoice_tax_note',
'account_move_name_sequence',
'account_netting',
'account_payment',
'account_payment_method_base',
'account_payment_mode',
'account_payment_order',
'account_payment_order_grouped_output',
'account_payment_purchase',
'account_payment_sale',
'account_peppol',
'account_peppol_response',
'account_qr_code_sepa',
'account_reconcile_oca',
'account_statement_base',
'account_statement_import_base',
'account_statement_import_file',
'account_statement_import_online',
'account_tax_balance',
'account_usability',
'analytic',
'api_doc',
'auth_passkey',
'auth_passkey_portal',
'auth_signup',
'auth_totp',
'auth_totp_mail',
'auth_totp_portal',
'barcodes',
'barcodes_gs1_nomenclature',
'base',
'base_address_extended',
'base_bank_from_iban',
'base_comment_template',
'base_geolocalize',
'base_iban',
'base_import',
'base_import_module',
'base_install_request',
'base_location',
'base_location_geonames_import',
'base_partner_sequence',
'base_setup',
'base_technical_features',
'base_vat',
'board',
'bus',
'calendar',
'calendar_sms',
'certificate',
'cloud_storage',
'contacts',
'date_range',
'digest',
'disable_odoo_online',
'document_knowledge',
'document_page',
'document_page_partner',
'document_url',
'event',
'event_product',
'event_sale',
'event_sms',
'google_gmail',
'google_recaptcha',
'hr',
'hr_attendance',
'hr_calendar',
'hr_expense',
'hr_holidays',
'hr_holidays_attendance',
'hr_holidays_homeworking',
'hr_homeworking',
'hr_homeworking_calendar',
'hr_org_chart',
'hr_presence',
'hr_skills',
'hr_skills_event',
'html_builder',
'html_editor',
'http_routing',
'iap',
'iap_mail',
'l10n_es',
'l10n_es_account_banking_sepa_fsdd',
'l10n_es_account_statement_import_n43',
'l10n_es_aeat',
'l10n_es_aeat_mod111',
'l10n_es_aeat_mod115',
'l10n_es_aeat_mod303',
'l10n_es_aeat_mod347',
'l10n_es_aeat_mod349',
'l10n_es_aeat_mod390',
'l10n_es_aeat_partner_check',
'l10n_es_edi_facturae',
'l10n_es_partner',
'l10n_es_toponyms',
'link_tracker',
'mail',
'mail_bot',
'mail_bot_hr',
'mass_mailing',
'mass_mailing_event',
'mass_mailing_sale',
'mass_mailing_themes',
'microsoft_outlook',
'mrp',
'mrp_account',
'onboarding',
'partner_autocomplete',
'partner_statement',
'payment',
'phone_validation',
'portal',
'portal_rating',
'privacy_lookup',
'product',
'project',
'project_account',
'project_hr_expense',
'project_hr_skills',
'project_mrp',
'project_mrp_account',
'project_mrp_sale',
'project_purchase',
'project_purchase_stock',
'project_sale_expense',
'project_sms',
'project_stock',
'project_stock_account',
'project_task_note',
'project_timeline',
'project_todo',
'purchase',
'purchase_edi_ubl_bis3',
'purchase_force_invoiced',
'purchase_mrp',
'purchase_product_template_tags',
'purchase_request',
'purchase_stock',
'rating',
'remove_odoo_enterprise',
'report_xlsx',
'report_xlsx_helper',
'resource',
'resource_mail',
'rpc',
'sale',
'sale_edi_ubl',
'sale_expense',
'sale_management',
'sale_mrp',
'sale_pdf_quote_builder',
'sale_project',
'sale_project_stock',
'sale_project_stock_account',
'sale_purchase',
'sale_purchase_project',
'sale_purchase_stock',
'sale_service',
'sale_sms',
'sale_stock',
'sales_team',
'sms',
'snailmail',
'snailmail_account',
'social_media',
'spreadsheet',
'spreadsheet_account',
'spreadsheet_dashboard',
'spreadsheet_dashboard_account',
'spreadsheet_dashboard_event_sale',
'spreadsheet_dashboard_hr_expense',
'spreadsheet_dashboard_sale',
'spreadsheet_dashboard_stock_account',
'stock',
'stock_account',
'stock_sms',
'uom',
'utm',
'web',
'web_hierarchy',
'web_responsive',
'web_timeline',
'web_tour',
'web_unsplash',
        
    
                
                
                ],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}

